name: GithubDeployment

on:
  push: 
    branches:
      - 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
            touch .env
            echo VITE_API_KEY=${{secrets.FIREBASE_API_KEY}} >> .env
            echo VITE_AUTH_DOMAIN=${{secrets.FIREBASE_AUTH_DOMAIN}} >> .env
            echo VITE_DB_URL=${{secrets.FIREBASE_DB_URL}} >> .env
            echo VITE_PROJECT_ID=${{secrets.FIREBASE_PROJECT_ID}} >> .env
            echo VITE_STORAGE_BUCKET=${{secrets.FIREBASE_STORAGE_BUCKET}} >> .env
            echo VITE_MESSAGING_SENDER_ID=${{secrets.FIREBASE_MESSAGING_SENDER_ID}} >> .env
            echo VITE_APP_ID=${{secrets.FIREBASE_APP_ID}} >> .env
            echo VITE_MEASUREMENT_ID=${{secrets.FIREBASE_MEASUREMENT_ID}} >> .env
            echo VITE_EMAIL_SERVICE_ID=${{secrets.EMAIL_SERVICE_ID}} >> .env
            echo VITE_EMAIL_TEMPLATE_ID=${{secrets.EMAIL_TEMPLATE_ID}} >> .env
            echo VITE_EMAIL_PUBLIC_KEY=${{secrets.EMAIL_PUBLIC_KEY}} >> .env

      - name: Install dependencies
        run: yarn install
        
      - name: Deploy
        env:
          MY_EMAIL: yoonhj97@naver.com
          MY_NAME: ohdal
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{ secrets.ACCESS_TOKEN }}@github.com/ohdal/Susim.git
          yarn deploy_git -u "github-actions-bot <support+actions@github.com>"
